import { SeedData } from "../../ui/features/product";
import { Role } from "../../modules/auth/domain/model/role";

export const initialData: SeedData = {
  countries: [
    { name: "Afganistán", id: "AF" },
    { name: "Islas Åland", id: "AX" },
    { name: "Albania", id: "AL" },
    { name: "Argelia", id: "DZ" },
    { name: "Samoa Americana", id: "AS" },
    { name: "Andorra", id: "AD" },
    { name: "Angola", id: "AO" },
    { name: "Anguila", id: "AI" },
    { name: "Antártida", id: "AQ" },
    { name: "Antigua y Barbuda", id: "AG" },
    { name: "Argentina", id: "AR" },
    { name: "Armenia", id: "AM" },
    { name: "Aruba", id: "AW" },
    { name: "Australia", id: "AU" },
    { name: "Austria", id: "AT" },
    { name: "Azerbaiyán", id: "AZ" },
    { name: "Bahamas", id: "BS" },
    { name: "Baréin", id: "BH" },
    { name: "Bangladés", id: "BD" },
    { name: "Barbados", id: "BB" },
    { name: "Bielorrusia", id: "BY" },
    { name: "Bélgica", id: "BE" },
    { name: "Belice", id: "BZ" },
    { name: "Benín", id: "BJ" },
    { name: "Bermudas", id: "BM" },
    { name: "Bután", id: "BT" },
    { name: "Bolivia", id: "BO" },
    { name: "Bosnia y Herzegovina", id: "BA" },
    { name: "Botsuana", id: "BW" },
    { name: "Isla Bouvet", id: "BV" },
    { name: "Brasil", id: "BR" },
    { name: "Territorio Británico del Océano Índico", id: "IO" },
    { name: "Brunéi", id: "BN" },
    { name: "Bulgaria", id: "BG" },
    { name: "Burkina Faso", id: "BF" },
    { name: "Burundi", id: "BI" },
    { name: "Camboya", id: "KH" },
    { name: "Camerún", id: "CM" },
    { name: "Canadá", id: "CA" },
    { name: "Cabo Verde", id: "CV" },
    { name: "Islas Caimán", id: "KY" },
    { name: "República Centroafricana", id: "CF" },
    { name: "Chad", id: "TD" },
    { name: "Chile", id: "CL" },
    { name: "China", id: "CN" },
    { name: "Isla de Navidad", id: "CX" },
    { name: "Islas Cocos (Keeling)", id: "CC" },
    { name: "Colombia", id: "CO" },
    { name: "Comoras", id: "KM" },
    { name: "Congo", id: "CG" },
    { name: "República Democrática del Congo", id: "CD" },
    { name: "Islas Cook", id: "CK" },
    { name: "Costa Rica", id: "CR" },
    { name: "Costa de Marfil", id: "CI" },
    { name: "Croacia", id: "HR" },
    { name: "Cuba", id: "CU" },
    { name: "Chipre", id: "CY" },
    { name: "Chequia", id: "CZ" },
    { name: "Dinamarca", id: "DK" },
    { name: "Yibuti", id: "DJ" },
    { name: "Dominica", id: "DM" },
    { name: "República Dominicana", id: "DO" },
    { name: "Ecuador", id: "EC" },
    { name: "Egipto", id: "EG" },
    { name: "El Salvador", id: "SV" },
    { name: "Guinea Ecuatorial", id: "GQ" },
    { name: "Eritrea", id: "ER" },
    { name: "Estonia", id: "EE" },
    { name: "Etiopía", id: "ET" },
    { name: "Islas Malvinas", id: "FK" },
    { name: "Islas Feroe", id: "FO" },
    { name: "Fiyi", id: "FJ" },
    { name: "Finlandia", id: "FI" },
    { name: "Francia", id: "FR" },
    { name: "Guayana Franciasa", id: "GF" },
    { name: "Polinesia Franciasa", id: "PF" },
    { name: "Territorios Australes Franciases", id: "TF" },
    { name: "Gabón", id: "GA" },
    { name: "Gambia", id: "GM" },
    { name: "Georgia", id: "GE" },
    { name: "Alemania", id: "DE" },
    { name: "Ghana", id: "GH" },
    { name: "Gibraltar", id: "GI" },
    { name: "Grecia", id: "GR" },
    { name: "Groenlandia", id: "GL" },
    { name: "Granada", id: "GD" },
    { name: "Guadalupe", id: "GP" },
    { name: "Guam", id: "GU" },
    { name: "Guatemala", id: "GT" },
    { name: "Guernsey", id: "GG" },
    { name: "Guinea", id: "GN" },
    { name: "Guinea-Bisáu", id: "GW" },
    { name: "Guyana", id: "GY" },
    { name: "Haití", id: "HT" },
    { name: "Islas Heard y McDonald", id: "HM" },
    { name: "Santa Sede (Estado de la Ciudad del Vaticano)", id: "VA" },
    { name: "Honduras", id: "HN" },
    { name: "Hong Kong", id: "HK" },
    { name: "Hungría", id: "HU" },
    { name: "Islandia", id: "IS" },
    { name: "India", id: "IN" },
    { name: "Indonesia", id: "ID" },
    { name: "Irán, República Islámica de", id: "IR" },
    { name: "Irak", id: "IQ" },
    { name: "Irlanda", id: "IE" },
    { name: "Isla de Man", id: "IM" },
    { name: "Israel", id: "IL" },
    { name: "Italia", id: "IT" },
    { name: "Jamaica", id: "JM" },
    { name: "Japón", id: "JP" },
    { name: "Jersey", id: "JE" },
    { name: "Jordania", id: "JO" },
    { name: "Kazajistán", id: "KZ" },
    { name: "Kenia", id: "KE" },
    { name: "Kiribati", id: "KI" },
    { name: "Corea, República Popular Democrática de", id: "KP" },
    { name: "Corea del Sur", id: "KR" },
    { name: "Kuwait", id: "KW" },
    { name: "Kirguistán", id: "KG" },
    { name: "República Democrática Popular Lao", id: "LA" },
    { name: "Letonia", id: "LV" },
    { name: "Líbano", id: "LB" },
    { name: "Lesoto", id: "LS" },
    { name: "Liberia", id: "LR" },
    { name: "Jamahiriya Árabe Libia", id: "LY" },
    { name: "Liechtenstein", id: "LI" },
    { name: "Lituania", id: "LT" },
    { name: "Luxemburgo", id: "LU" },
    { name: "Macao", id: "MO" },
    { name: "Macedonia, Ex República Yugoslava de", id: "MK" },
    { name: "Madagascar", id: "MG" },
    { name: "Malaui", id: "MW" },
    { name: "Malasia", id: "MY" },
    { name: "Maldivas", id: "MV" },
    { name: "Malí", id: "ML" },
    { name: "Malta", id: "MT" },
    { name: "Islas Marshall", id: "MH" },
    { name: "Martinica", id: "MQ" },
    { name: "Mauritania", id: "MR" },
    { name: "Mauricio", id: "MU" },
    { name: "Mayotte", id: "YT" },
    { name: "México", id: "MX" },
    { name: "Micronesia, Estados Federados de", id: "FM" },
    { name: "Moldavia, República de", id: "MD" },
    { name: "Mónaco", id: "MC" },
    { name: "Mongolia", id: "MN" },
    { name: "Montserrat", id: "MS" },
    { name: "Marruecos", id: "MA" },
    { name: "Mozambique", id: "MZ" },
    { name: "Myanmar", id: "MM" },
    { name: "Namibia", id: "NA" },
    { name: "Nauru", id: "NR" },
    { name: "Nepal", id: "NP" },
    { name: "Países Bajos", id: "NL" },
    { name: "Antillas Neerlandesas", id: "AN" },
    { name: "Nueva Caledonia", id: "NC" },
    { name: "Nueva Zelanda", id: "NZ" },
    { name: "Nicaragua", id: "NI" },
    { name: "Níger", id: "NE" },
    { name: "Nígeria", id: "NG" },
    { name: "Niue", id: "NU" },
    { name: "Isla Norfolk", id: "NF" },
    { name: "Islas Marianas del Norte", id: "MP" },
    { name: "Noruega", id: "NO" },
    { name: "Omán", id: "OM" },
    { name: "Pakistán", id: "PK" },
    { name: "Palaos", id: "PW" },
    { name: "Territorio Palestino Ocupado", id: "PS" },
    { name: "Panamá", id: "PA" },
    { name: "Papúa Nueva Guinea", id: "PG" },
    { name: "Paraguay", id: "PY" },
    { name: "Perú", id: "PE" },
    { name: "Filipinas", id: "PH" },
    { name: "Islas Pitcairn", id: "PN" },
    { name: "Polonia", id: "PL" },
    { name: "Portugal", id: "PT" },
    { name: "Puerto Rico", id: "PR" },
    { name: "Catar", id: "QA" },
    { name: "Reunión", id: "RE" },
    { name: "Rumanía", id: "RO" },
    { name: "Federación de Rusia", id: "RU" },
    { name: "Ruanda", id: "RW" },
    { name: "Santa Elena", id: "SH" },
    { name: "San Cristóbal y Nieves", id: "KN" },
    { name: "Santa Lucía", id: "LC" },
    { name: "San Pedro y Miquelón", id: "PM" },
    { name: "San Vicente y las Granadinas", id: "VC" },
    { name: "Samoa", id: "WS" },
    { name: "San Marino", id: "SM" },
    { name: "Santo Tomé y Príncipe", id: "ST" },
    { name: "Arabia Saudita", id: "SA" },
    { name: "Senegal", id: "SN" },
    { name: "Serbia y Montenegro", id: "CS" },
    { name: "Seychelles", id: "SC" },
    { name: "Sierra Leona", id: "SL" },
    { name: "Singapur", id: "SG" },
    { name: "Eslovaquia", id: "SK" },
    { name: "Eslovenia", id: "SI" },
    { name: "Islas Salomón", id: "SB" },
    { name: "Somalia", id: "SO" },
    { name: "Sudáfrica", id: "ZA" },
    { name: "Islas Georgias del Sur y Sandwich del Sur", id: "GS" },
    { name: "España", id: "ES" },
    { name: "Sri Lanka", id: "LK" },
    { name: "Sudán", id: "SD" },
    { name: "Surinam", id: "SR" },
    { name: "Svalbard and Jan Mayen", id: "SJ" },
    { name: "Suazilandia", id: "SZ" },
    { name: "Suecia", id: "SE" },
    { name: "Suiza", id: "CH" },
    { name: "República Árabe Siria", id: "SY" },
    { name: "Taiwán, Provincia de China", id: "TW" },
    { name: "Tayikistán", id: "TJ" },
    { name: "Tanzania, República Unida de", id: "TZ" },
    { name: "Tailandia", id: "TH" },
    { name: "Timor Oriental", id: "TL" },
    { name: "Togo", id: "TG" },
    { name: "Tokelau", id: "TK" },
    { name: "Tonga", id: "TO" },
    { name: "Trinidad y Tobago", id: "TT" },
    { name: "Túnez", id: "TN" },
    { name: "Turquía", id: "TR" },
    { name: "Turkmenistán", id: "TM" },
    { name: "Islas Turcas y Caicos", id: "TC" },
    { name: "Tuvalu", id: "TV" },
    { name: "Uganda", id: "UG" },
    { name: "Ucrania", id: "UA" },
    { name: "Emiratos Árabes Unidos", id: "AE" },
    { name: "Reino Unido", id: "GB" },
    { name: "Estados Unidos", id: "US" },
    { name: "Islas Ultramarinas Menores de los Estados Unidos", id: "UM" },
    { name: "Uruguay", id: "UY" },
    { name: "Uzbekistán", id: "UZ" },
    { name: "Vanuatu", id: "VU" },
    { name: "Venezuela", id: "VE" },
    { name: "Vietnam", id: "VN" },
    { name: "Islas Vírgenes Británicas", id: "VG" },
    { name: "Islas Vírgenes de los Estados Unidos", id: "VI" },
    { name: "Wallis y Futuna", id: "WF" },
    { name: "Sáhara Occidental", id: "EH" },
    { name: "Yemen", id: "YE" },
    { name: "Zambia", id: "ZM" },
    { name: "Zimbabue", id: "ZW" },
  ],
  categories: ["shirts", "pants", "hoodies", "hats"],
  users: [
    {
      name: "Admin Teslo",
      email: "admin@teslo.shop",
      password: "$2b$10$qkHgrnognGr30k8CNlRmQei0TfUwpwLDzzFDYZSkrK6GLx1YkVS9K",
      role: Role.admin,
      image: "",
      emailVerified: new Date(),
      emailVerificationToken: null,
      emailVerificationExpires: null,
    },
    {
      name: "Juan Pérez",
      email: "juan.perez@teslo.shop",
      password: "$2b$10$qkHgrnognGr30k8CNlRmQei0TfUwpwLDzzFDYZSkrK6GLx1YkVS9K",
      role: Role.user,
      image: "",
      emailVerified: new Date(),
      emailVerificationToken: null,
      emailVerificationExpires: null,
    },
    {
      name: "María Gómez",
      email: "maria.gomez@teslo.shop",
      password: "$2b$10$qkHgrnognGr30k8CNlRmQei0TfUwpwLDzzFDYZSkrK6GLx1YkVS9K",
      role: Role.user,
      image: "",
      emailVerified: null,
      emailVerificationToken: "8f4b2c1e9a7d4f6b3c5a2e8d1f7b4c6a",
      emailVerificationExpires: new Date(Date.now() + 24 * 60 * 60 * 1000),
    },
    {
      name: "Carlos Rodríguez",
      email: "carlos.rodriguez@teslo.shop",
      password: "$2b$10$qkHgrnognGr30k8CNlRmQei0TfUwpwLDzzFDYZSkrK6GLx1YkVS9K",
      role: Role.user,
      image: "",
      emailVerified: null,
      emailVerificationToken: "3a9c8d5e7f1b4a2c6e8d0f5b7a3c9e1f",
      emailVerificationExpires: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      name: "Lucía Fernández",
      email: "lucia.fernandez@teslo.shop",
      password: "$2b$10$qkHgrnognGr30k8CNlRmQei0TfUwpwLDzzFDYZSkrK6GLx1YkVS9K",
      role: Role.admin,
      image: "",
      emailVerified: null,
      emailVerificationToken: null,
      emailVerificationExpires: null,
    },
  ],
  products: [
    {
      description:
        "Presentamos la colección Tesla Chill. La sudadera de cuello redondo Chill para hombre tiene un exterior premium de gran peso y un interior de felpa suave para mayor comodidad en cualquier temporada. La sudadera presenta un sutil logo T de poliuretano termoplástico en el pecho y el logotipo de Tesla bajo el cuello trasero. Confeccionada con 60% algodón y 40% poliéster reciclado.",
      images: ["1740176-00-A_0_2000.jpg", "1740176-00-A_1.jpg"],
      inStock: 7,
      price: 75,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "mens_chill_crew_neck_sweatshirt",
      type: "shirts",
      tags: ["sweatshirt"],
      title: "Sudadera de cuello redondo Chill para hombre",
      gender: "men",
    },
    {
      description:
        "La chaqueta camisera acolchada para hombre presenta un diseño acolchado de ajuste único para brindar calidez y movilidad en las temporadas de clima frío. Con una estética urbana general, la chaqueta incluye sutiles logos de Tesla inyectados con silicona bajo el cuello trasero y en la manga derecha, así como tiradores de cremallera personalizados de metal mate. Confeccionada con 87% nailon y 13% poliuretano.",
      images: ["1740507-00-A_0_2000.jpg", "1740507-00-A_1.jpg"],
      inStock: 5,
      price: 200,
      sizes: ["XS", "S", "M", "XL", "XXL"],
      slug: "men_quilted_shirt_jacket",
      type: "shirts",
      tags: ["jacket"],
      title: "Chaqueta camisera acolchada para hombre",
      gender: "men",
    },

    {
      description:
        "Presentamos la colección Tesla Raven. La chaqueta bomber ligera con cremallera Raven para hombre tiene una silueta moderna y premium confeccionada con una mezcla sostenible de bambú y algodón para adaptarse a cualquier temporada. La chaqueta presenta sutiles logos de Tesla de poliuretano termoplástico en el pecho izquierdo y bajo el cuello trasero, un bolsillo interior oculto con tiradores de cremallera personalizados de metal mate e interior de tejido francés. Confeccionada con 70% bambú y 30% algodón.",
      images: ["1740250-00-A_0_2000.jpg", "1740250-00-A_1.jpg"],
      inStock: 10,
      price: 130,
      sizes: ["S", "M", "L", "XL", "XXL"],
      slug: "men_raven_lightweight_zip_up_bomber_jacket",
      type: "shirts",
      tags: ["shirt"],
      title: "Chaqueta bomber ligera con cremallera Raven para hombre",
      gender: "men",
    },

    {
      description:
        "Presentamos la colección Tesla Turbine. Diseñada para el estilo, la comodidad y el uso diario, la camiseta de manga larga Turbine para hombre presenta un sutil logo T a base de agua en el pecho izquierdo y el logotipo de Tesla bajo el cuello trasero. El material ligero está teñido dos veces, creando un estilo suave y casual ideal para cualquier temporada. Confeccionada con 50% algodón y 50% poliéster.",
      images: ["1740280-00-A_0_2000.jpg", "1740280-00-A_1.jpg"],
      inStock: 50,
      price: 45,
      sizes: ["XS", "S", "M", "L"],
      slug: "men_turbine_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de manga larga Turbine para hombre",
      gender: "men",
    },
    {
      description:
        "Presentamos la colección Tesla Turbine. Diseñada para el estilo, la comodidad y el uso diario, la camiseta de manga corta Turbine para hombre presenta un sutil logotipo de Tesla a base de agua en el pecho y el logo T bajo el cuello trasero. El material ligero está teñido dos veces, creando un estilo suave y casual ideal para cualquier temporada. Confeccionada con 50% algodón y 50% poliéster.",
      images: ["1741416-00-A_0_2000.jpg", "1741416-00-A_1.jpg"],
      inStock: 50,
      price: 40,
      sizes: ["M", "L", "XL", "XXL"],
      slug: "men_turbine_short_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de manga corta Turbine para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para la comodidad, la camiseta Cybertruck Owl está confeccionada con 100% algodón y presenta nuestro icónico icono de Cybertruck en la parte trasera.",
      images: ["7654393-00-A_2_2000.jpg", "7654393-00-A_3.jpg"],
      inStock: 0,
      price: 35,
      sizes: ["M", "L", "XL", "XXL"],
      slug: "men_cybertruck_owl_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Cybertruck Owl para hombre",
      gender: "men",
    },
    {
      description:
        "Inspirada en nuestro sistema doméstico integrado de energía solar y almacenamiento, la camiseta Tesla Solar Roof promueve la energía limpia y sostenible dondequiera que vayas. Diseñada para el ajuste, la comodidad y el estilo, la camiseta presenta una vista aérea de nuestro diseño integral Solar Roof en el frente, con el icónico logo T sobre 'Solar Roof' en la parte trasera. Confeccionada con 100% algodón peruano.",
      images: ["1703767-00-A_0_2000.jpg", "1703767-00-A_1.jpg"],
      inStock: 15,
      price: 35,
      sizes: ["S", "M", "L", "XL"],
      slug: "men_solar_roof_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Solar Roof para hombre",
      gender: "men",
    },
    {
      description:
        "Inspirada en el recurso más ilimitado del mundo, la camiseta Let the Sun Shine resalta nuestro sistema doméstico integrado de energía solar y almacenamiento. Diseñada para el ajuste, la comodidad y el estilo, la camiseta presenta un gráfico de atardecer junto con el logotipo de Tesla en el frente y el icónico logo T impreso sobre 'Solar Roof' en la parte trasera. Confeccionada con 100% algodón peruano.",
      images: ["1700280-00-A_0_2000.jpg", "1700280-00-A_1.jpg"],
      inStock: 17,
      price: 35,
      sizes: ["XS", "S", "XL", "XXL"],
      slug: "men_let_the_sun_shine_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Let the Sun Shine para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para el ajuste, la comodidad y el estilo, la camiseta con logotipo grande en 3D para hombre está confeccionada con 100% algodón peruano y presenta el logotipo de Tesla impreso en 3D con silicona en el pecho.",
      images: ["8764734-00-A_0_2000.jpg", "8764734-00-A_1.jpg"],
      inStock: 12,
      price: 35,
      sizes: ["XS", "S", "M"],
      slug: "men_3d_large_wordmark_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta con logotipo grande en 3D para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para el ajuste, la comodidad y el estilo, la camiseta con logo T de Tesla está confeccionada con 100% algodón peruano y presenta un logo T impreso con silicona en el pecho izquierdo.",
      images: ["7652426-00-A_0_2000.jpg", "7652426-00-A_1.jpg"],
      inStock: 5,
      price: 35,
      sizes: ["XS", "S"],
      slug: "men_3d_t_logo_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta con logo T en 3D para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para la comodidad y el estilo en cualquier talla, la camiseta con logotipo pequeño de Tesla está confeccionada con 100% algodón peruano y presenta un logotipo impreso en 3D con silicona en el pecho izquierdo.",
      images: ["8528839-00-A_0_2000.jpg", "8528839-00-A_2.jpg"],
      inStock: 2,
      price: 35,
      sizes: ["XS", "S", "M"],
      slug: "men_3d_small_wordmark_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta con logotipo pequeño en 3D para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para celebrar el increíble modo de rendimiento de Tesla, la camiseta Plaid Mode ofrece un excelente ajuste, comodidad y estilo. Confeccionada con 100% algodón, es lo más parecido a viajar en el asiento del copiloto en el Nürburgring.",
      images: ["1549268-00-A_0_2000.jpg", "1549268-00-A_2.jpg"],
      inStock: 82,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "men_plaid_mode_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Plaid Mode para hombre",
      gender: "men",
    },
    {
      description:
        "Inspirada en nuestra popular batería doméstica, la camiseta Tesla Powerwall está confeccionada con 100% algodón y presenta la frase 'Pure Energy' bajo el logotipo de la parte trasera. Diseñada para el ajuste, la comodidad y el estilo, esta camiseta exclusiva promueve la energía sostenible en cualquier entorno.",
      images: ["9877034-00-A_0_2000.jpg", "9877034-00-A_2.jpg"],
      inStock: 24,
      price: 35,
      sizes: ["XL", "XXL"],
      slug: "men_powerwall_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Powerwall para hombre",
      gender: "men",
    },
    {
      description:
        "Inspirada en el Tesla Battery Day y con la celda de batería sin pestañas presentada en el evento, la camiseta Battery Day celebra el futuro del almacenamiento de energía y la fabricación de celdas. Diseñada para el ajuste, la comodidad y el estilo, la camiseta Battery Day está confeccionada con 100% algodón y presenta una celda estilizada impresa en el pecho. Fabricada en Perú.",
      images: ["1633802-00-A_0_2000.jpg", "1633802-00-A_2.jpg"],
      inStock: 5,
      price: 30,
      sizes: ["XS", "S", "XXL"],
      slug: "men_battery_day_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Battery Day para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para una comodidad excepcional e inspirada en el evento de presentación del Cybertruck, la camiseta Cybertruck Bulletproof está confeccionada con 100% algodón y presenta nuestro icónico icono de Cybertruck en la parte trasera.",
      images: ["7654399-00-A_0_2000.jpg", "7654399-00-A_1.jpg"],
      inStock: 150,
      price: 30,
      sizes: ["M", "L"],
      slug: "men_cybertruck_bulletproof_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Cybertruck Bulletproof para hombre",
      gender: "men",
    },
    {
      description:
        "Inspirada en el gráfico de confirmación de pedido del Model Y, la camiseta de edición limitada Haha Yes está diseñada para la comodidad y el estilo. Confeccionada con 100% algodón peruano y con el logotipo de Tesla en el pecho, esta camiseta exclusiva conmemorará tu pedido durante años.",
      images: ["7652410-00-A_0.jpg", "7652410-00-A_1_2000.jpg"],
      inStock: 10,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "men_haha_yes_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Haha Yes para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para el ajuste, la comodidad y el estilo, la camiseta de edición limitada S3XY está confeccionada con 100% algodón y presenta el logo 'S3XY' impreso en 3D con silicona en el pecho. Fabricada en Perú. Disponible en negro.",
      images: ["8764600-00-A_0_2000.jpg", "8764600-00-A_2.jpg"],
      inStock: 34,
      price: 35,
      sizes: ["XS", "S", "M", "L"],
      slug: "men_s3xy_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta S3XY para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para el ajuste, la comodidad y el estilo, la camiseta de manga larga con logotipo en 3D para hombre está confeccionada con 100% algodón y presenta un sobrio logotipo en el pecho izquierdo.",
      images: ["8764813-00-A_0_2000.jpg", "8764813-00-A_1.jpg"],
      inStock: 15,
      price: 40,
      sizes: ["XL", "XXL"],
      slug: "men_3d_wordmark_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de manga larga con logotipo en 3D para hombre",
      gender: "men",
    },
    {
      description:
        "Diseñada para el ajuste, la comodidad y el estilo, la camiseta de manga larga con logo T en 3D para hombre está confeccionada con 100% algodón y presenta un sobrio logo T en el pecho izquierdo.",
      images: ["8529198-00-A_0_2000.jpg", "8529198-00-A_1.jpg"],
      inStock: 12,
      price: 40,
      sizes: ["XS", "XXL"],
      slug: "men_3d_t_logo_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de manga larga con logo T en 3D para hombre",
      gender: "men",
    },
    {
      description:
        "Presentamos la colección Tesla Raven. La sudadera ligera Raven para hombre tiene una silueta relajada y premium confeccionada con una mezcla sostenible de bambú y algodón. La sudadera presenta sutiles logos de Tesla de poliuretano termoplástico en el pecho y en la manga, y un interior de tejido francés para adaptarse a cualquier temporada. Confeccionada con 70% bambú y 30% algodón.",
      images: ["1740245-00-A_0_2000.jpg", "1740245-00-A_1.jpg"],
      inStock: 10,
      price: 115,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "men_raven_lightweight_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Sudadera ligera Raven para hombre",
      gender: "men",
    },
    {
      description:
        "Presentamos la colección Tesla Chill. La sudadera con capucha Chill tiene un exterior premium de gran peso y un interior de felpa suave para mayor comodidad en cualquier temporada. Esta sudadera unisex presenta sutiles logos de Tesla de poliuretano termoplástico en el pecho y en la manga, una capucha de doble capa y costura única, y bolsillos con tiradores de cremallera personalizados de metal mate. Confeccionada con 60% algodón y 40% poliéster reciclado.",
      images: ["1740051-00-A_0_2000.jpg", "1740051-00-A_1.jpg"],
      inStock: 10,
      price: 130,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "chill_pullover_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Sudadera con capucha Chill",
      gender: "unisex",
    },
    {
      description:
        "Presentamos la colección Tesla Chill. La sudadera con capucha y cremallera completa Chill para hombre tiene un exterior premium de gran peso y un interior de felpa suave para mayor comodidad en cualquier temporada. La sudadera presenta sutiles logos de Tesla de poliuretano termoplástico en el pecho izquierdo y en la manga, una capucha de doble capa y costura única, y bolsillos con tiradores de cremallera personalizados de metal mate. Confeccionada con 60% algodón y 40% poliéster reciclado.",
      images: ["1741111-00-A_0_2000.jpg", "1741111-00-A_1.jpg"],
      inStock: 100,
      price: 85,
      sizes: ["XS", "L", "XL", "XXL"],
      slug: "men_chill_full_zip_hoodie",
      type: "shirts",
      tags: ["shirt"],
      title: "Sudadera con capucha y cremallera completa Chill para hombre",
      gender: "men",
    },
    {
      description:
        "Presentamos la colección Tesla Chill. La sudadera con cremallera de cuarto Chill para hombre tiene un exterior premium de gran peso y un interior de felpa suave para mayor comodidad en cualquier temporada. La sudadera presenta sutiles logos de Tesla de poliuretano termoplástico en el pecho izquierdo y bajo el cuello trasero, así como un tirador de cremallera personalizado de metal mate. Confeccionada con 60% algodón y 40% poliéster reciclado.",
      images: ["1740140-00-A_0_2000.jpg", "1740140-00-A_1.jpg"],
      inStock: 7,
      price: 85,
      sizes: ["XS", "S", "M"],
      slug: "men_chill_quarter_zip_pullover_-_gray",
      type: "shirts",
      tags: ["shirt"],
      title: "Sudadera con cremallera de cuarto Chill para hombre - Gris",
      gender: "men",
    },
    {
      description:
        "Presentamos la colección Tesla Chill. La sudadera con cremallera de cuarto Chill para hombre tiene un exterior premium de gran peso y un interior de felpa suave para mayor comodidad en cualquier temporada. La sudadera presenta sutiles logos de Tesla de poliuretano termoplástico en el pecho izquierdo y bajo el cuello trasero, así como un tirador de cremallera personalizado de metal mate. Confeccionada con 60% algodón y 40% poliéster reciclado.",
      images: ["1740145-00-A_2_2000.jpg", "1740145-00-A_1.jpg"],
      inStock: 15,
      price: 85,
      sizes: ["XS", "S", "M", "L"],
      slug: "men_chill_quarter_zip_pullover_-_white",
      type: "shirts",
      tags: ["shirt"],
      title: "Sudadera con cremallera de cuarto Chill para hombre - Blanco",
      gender: "men",
    },
    {
      description:
        "La sudadera con capucha de logotipo grande en 3D unisex presenta felpa suave y una capucha ajustable forrada en jersey para mayor comodidad y cobertura. Diseñada en estilo unisex, la sudadera con capucha incluye un logotipo impreso en 3D con silicona en tono sobre tono en el pecho.",
      images: ["8529107-00-A_0_2000.jpg", "8529107-00-A_1.jpg"],
      inStock: 15,
      price: 70,
      sizes: ["XS", "S", "XL", "XXL"],
      slug: "3d_large_wordmark_pullover_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Sudadera con capucha de logotipo grande en 3D",
      gender: "unisex",
    },
    {
      description:
        "Al igual que el icónico logotipo de Tesla, la sudadera Cybertruck Graffiti es un clásico en ciernes. Estilo unisex con felpa suave y una capucha ajustable forrada en jersey para una cobertura cómoda.",
      images: ["7654420-00-A_0_2000.jpg", "7654420-00-A_1_2000.jpg"],
      inStock: 13,
      price: 60,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "cybertruck_graffiti_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Sudadera Cybertruck Graffiti",
      gender: "unisex",
    },
    {
      description:
        "La gorra Relaxed con logo T combina una silueta clásica con detalles modernos, con un logo T en 3D y un cierre de hebilla metálica personalizada. El diseño ultrasuave es flexible y resistente a la abrasión, mientras que la banda interior para el sudor incluye un acolchado quiltado para mayor comodidad y absorción de la humedad. La visera está fabricada íntegramente con botellas de plástico reciclado. 100% algodón.",
      images: ["1657932-00-A_0_2000.jpg", "1657932-00-A_1.jpg"],
      inStock: 11,
      price: 30,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "relaxed_t_logo_hat",
      type: "hats",
      tags: ["hats"],
      title: "Gorra Relaxed con logo T",
      gender: "unisex",
    },
    {
      description:
        "La gorra Relaxed con logo T combina una silueta clásica con detalles modernos, con un logo T en 3D y un cierre de hebilla metálica personalizada. El diseño ultrasuave es flexible y resistente a la abrasión, mientras que la banda interior para el sudor incluye un acolchado quiltado para mayor comodidad y absorción de la humedad. La visera está fabricada íntegramente con botellas de plástico reciclado. 100% algodón.",
      images: ["1740417-00-A_0_2000.jpg", "1740417-00-A_1.jpg"],
      inStock: 13,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "thermal_cuffed_beanie",
      type: "hats",
      tags: ["hats"],
      title: "Gorro térmico de puño",
      gender: "unisex",
    },
    {
      description:
        "La chaqueta acolchada crop para mujer presenta una silueta recortada única para un estilo moderno y perfecto durante la próxima temporada de clima frío. La chaqueta acolchada incluye sutiles logos de Tesla inyectados con silicona bajo el cuello trasero y en la manga derecha, tiradores de cremallera personalizados de metal mate y un suave cuello forrado en felpa. Confeccionada con 87% nailon y 13% poliuretano.",
      images: ["1740535-00-A_0_2000.jpg", "1740535-00-A_1.jpg"],
      inStock: 85,
      price: 225,
      sizes: ["XS", "S", "M"],
      slug: "women_cropped_puffer_jacket",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Chaqueta acolchada crop para mujer",
      gender: "women",
    },
    {
      description:
        "Presentamos la colección Tesla Chill. La sudadera crop con media cremallera Chill para mujer tiene un exterior premium de felpa suave y una silueta recortada ideal para el uso diario. La sudadera presenta un dobladillo elástico que se ajusta en la cintura, sutiles logos de Tesla de poliuretano termoplástico a lo largo de la capucha y en la manga, una capucha de doble capa y costura única, y un tirador de cremallera anular personalizado. Confeccionada con 60% algodón y 40% poliéster reciclado.",
      images: ["1740226-00-A_0_2000.jpg", "1740226-00-A_1.jpg"],
      inStock: 10,
      price: 130,
      sizes: ["XS", "S", "M", "XXL"],
      slug: "women_chill_half_zip_cropped_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Sudadera crop con media cremallera Chill para mujer",
      gender: "women",
    },
    {
      description:
        "Presentamos la colección Tesla Raven. La sudadera holgada de cuello redondo Raven para mujer tiene una silueta relajada y premium confeccionada con una mezcla sostenible de bambú y algodón. La sudadera holgada presenta un sutil logotipo de Tesla de poliuretano termoplástico en la manga izquierda y un interior de tejido francés para un aspecto y una sensación acogedores en cada temporada. Combínala con tus Raven Joggers o con tu atuendo favorito para el día a día. Confeccionada con 70% bambú y 30% algodón.",
      images: ["1740260-00-A_0_2000.jpg", "1740260-00-A_1.jpg"],
      inStock: 9,
      price: 110,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_raven_slouchy_crew_sweatshirt",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Sudadera holgada de cuello redondo Raven para mujer",
      gender: "women",
    },
    {
      description:
        "Presentamos la colección Tesla Turbine. Diseñada para el estilo, la comodidad y el uso diario, la camiseta crop de manga larga Turbine para mujer presenta un sutil logotipo de Tesla a base de agua en el pecho y el logo T bajo el cuello trasero. El material ligero está teñido dos veces, creando un estilo suave y casual con una silueta recortada. Confeccionada con 50% algodón y 50%",
      images: ["1740290-00-A_0_2000.jpg", "1740290-00-A_1.jpg"],
      inStock: 10,
      price: 45,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_turbine_cropped_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta crop de manga larga Turbine para mujer",
      gender: "women",
    },
    {
      description:
        "Presentamos la colección Tesla Turbine. Diseñada para el estilo, la comodidad y el uso diario, la camiseta crop de manga corta Turbine para mujer presenta un sutil logotipo de Tesla a base de agua en el pecho y el logo T bajo el cuello trasero. El material ligero está teñido dos veces, creando un estilo suave y casual con una silueta recortada. Confeccionada con 50% algodón y 50% poliéster.",
      images: ["1741441-00-A_0_2000.jpg", "1741441-00-A_1.jpg"],
      inStock: 0,
      price: 40,
      sizes: ["XS", "S"],
      slug: "women_turbine_cropped_short_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta crop de manga corta Turbine para mujer",
      gender: "women",
    },
    {
      description:
        "Diseñada para el estilo y la comodidad, la ultrasuave camiseta de escote redondo y manga corta con logo T para mujer presenta un logo T en 3D impreso con silicona en tono sobre tono en el pecho izquierdo. Confeccionada con 50% algodón peruano y 50% viscosa peruana.",
      images: ["8765090-00-A_0_2000.jpg", "8765090-00-A_1.jpg"],
      inStock: 30,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_t_logo_short_sleeve_scoop_neck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de escote redondo y manga corta con logo T para mujer",
      gender: "women",
    },
    {
      description:
        "Diseñada para el estilo y la comodidad, la ultrasuave camiseta de escote redondo y manga larga con logo T para mujer presenta un logo T en 3D impreso con silicona en tono sobre tono en el pecho izquierdo. Confeccionada con 50% algodón peruano y 50% viscosa peruana.",
      images: ["8765100-00-A_0_2000.jpg", "8765100-00-A_1.jpg"],
      inStock: 16,
      price: 40,
      sizes: ["XS", "S", "L", "XL", "XXL"],
      slug: "women_t_logo_long_sleeve_scoop_neck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de escote redondo y manga larga con logo T para mujer",
      gender: "women",
    },
    {
      description:
        "Diseñada para el estilo y la comodidad, la camiseta de escote en V y manga corta con logotipo pequeño para mujer presenta un logotipo en 3D impreso con silicona en tono sobre tono en el pecho izquierdo. Confeccionada con 100% algodón peruano.",
      images: ["8765120-00-A_0_2000.jpg", "8765120-00-A_1.jpg"],
      inStock: 18,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_small_wordmark_short_sleeve_v-neck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de escote en V y manga corta con logotipo pequeño para mujer",
      gender: "women",
    },
    {
      description:
        "Diseñada para el estilo y la comodidad, la camiseta de cuello redondo y manga corta con logotipo grande para mujer presenta un logotipo en 3D impreso con silicona en tono sobre tono en el pecho. Confeccionada con 100% algodón pima peruano.",
      images: ["8765115-00-A_0_2000.jpg", "8765115-00-A_1.jpg"],
      inStock: 5,
      price: 35,
      sizes: ["XL", "XXL"],
      slug: "women_large_wordmark_short_sleeve_crew_neck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de cuello redondo y manga corta con logotipo grande para mujer",
      gender: "women",
    },
    {
      description:
        "Diseñada para celebrar el increíble modo de rendimiento de Tesla, la camiseta Plaid Mode ofrece un excelente ajuste, comodidad y estilo. Confeccionada con 100% algodón, es lo más parecido a viajar en el asiento del copiloto en el Nürburgring.",
      images: ["1549275-00-A_0_2000.jpg", "1549275-00-A_1.jpg"],
      inStock: 16,
      price: 35,
      sizes: ["S", "M"],
      slug: "women_plaid_mode_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Plaid Mode para mujer",
      gender: "women",
    },
    {
      description:
        "Inspirada en nuestra popular batería doméstica, la camiseta Tesla Powerwall está confeccionada con 100% algodón y presenta la frase 'Pure Energy' bajo el logotipo de la parte trasera. Diseñada para el ajuste, la comodidad y el estilo, esta camiseta exclusiva promueve la energía sostenible en cualquier",
      images: ["9877040-00-A_0_2000.jpg", "9877040-00-A_1.jpg"],
      inStock: 10,
      price: 130,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_powerwall_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Powerwall para mujer",
      gender: "women",
    },
    {
      description:
        "Totalmente personalizada y con un estilo único, la chaqueta Corp para mujer presenta un logo 'T' impreso con silicona en el pecho izquierdo y un destacado logotipo de Tesla en la espalda.",
      images: ["5645680-00-A_0_2000.jpg", "5645680-00-A_3.jpg"],
      inStock: 3,
      price: 90,
      sizes: ["M", "L", "XL", "XXL"],
      slug: "women_corp_jacket",
      type: "shirts",
      tags: ["shirt"],
      title: "Chaqueta Corp para mujer",
      gender: "women",
    },
    {
      description:
        "Presentamos la colección Tesla Raven. Los joggers Raven para mujer tienen una silueta relajada y premium confeccionada con una mezcla sostenible de bambú y algodón. Los joggers presentan un sutil logotipo de Tesla y el logo T de poliuretano termoplástico en la manga y un interior de tejido francés para un aspecto y una sensación acogedores en cada temporada. Combínalos con tu sudadera holgada de cuello redondo Raven, con tu chaqueta ligera con cremallera Raven o con tu atuendo favorito para el día a día. Confeccionados con 70% bambú y 30% algodón.",
      images: ["1740270-00-A_0_2000.jpg", "1740270-00-A_1.jpg"],
      inStock: 162,
      price: 100,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_raven_joggers",
      type: "shirts",
      tags: ["shirt"],
      title: "Joggers Raven para mujer",
      gender: "women",
    },
    {
      description:
        "Diseñada para el ajuste, la comodidad y el estilo, la camiseta de manga larga Cybertruck Graffiti para niño presenta un logotipo graffiti de Cybertruck a base de agua en el pecho, un logotipo de Tesla en la manga izquierda y el icónico logo T en el cuello trasero. Confeccionada con 50% algodón y 50% poliéster.",
      images: ["1742694-00-A_1_2000.jpg", "1742694-00-A_3.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_cybertruck_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta de manga larga Cybertruck para niño",
      gender: "kid",
    },
    {
      description:
        "La camiseta con logo T garabateado para niño está confeccionada con 100% algodón peruano y presenta un logo T de Tesla dibujado para que lo luzca todo pequeño artista.",
      images: ["8529312-00-A_0_2000.jpg", "8529312-00-A_1.jpg"],
      inStock: 0,
      price: 25,
      sizes: ["XS", "S", "M"],
      slug: "kids_scribble_t_logo_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta con logo T garabateado para niño",
      gender: "kid",
    },
    {
      description:
        "La camiseta Cybertruck para niño presenta el icónico logotipo graffiti de Cybertruck y está confeccionada con 100% algodón peruano para una comodidad máxima.",
      images: ["8529342-00-A_0_2000.jpg", "8529342-00-A_1.jpg"],
      inStock: 10,
      price: 25,
      sizes: ["XS", "S", "M"],
      slug: "kids_cybertruck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta Cybertruck para niño",
      gender: "kid",
    },
    {
      description:
        "La renovada camiseta con franja de carreras para niño está confeccionada con 100% algodón peruano y presenta una franja de carreras mejorada con un logotipo de Tesla cepillado, perfecta para cualquier corredor veloz.",
      images: ["8529354-00-A_0_2000.jpg", "8529354-00-A_1.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_racing_stripe_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta con franja de carreras para niño",
      gender: "kid",
    },
    {
      description:
        "Diseñada para el ajuste, la comodidad y el estilo, la camiseta con logo T de Tesla está confeccionada con 100% algodón peruano y presenta un logo T impreso con silicona en el pecho izquierdo.",
      images: ["7652465-00-A_0_2000.jpg", "7652465-00-A_1.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_3d_t_logo_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta con logo T en 3D para niño",
      gender: "kid",
    },
    {
      description:
        "La camiseta a cuadros está confeccionada con algodón peruano de fibra larga, libre de transgénicos. Perú es el único país del mundo donde el algodón se recolecta a mano a gran escala. La tradición de 4.500 años previene daños en la fibra durante el proceso de recolección y elimina la necesidad de usar químicos para abrir las plantas de algodón antes de la cosecha. Este proceso respetuoso con el medio ambiente produce un algodón suave, resistente y lustroso, y la camiseta se vuelve aún más suave con cada lavado.",
      images: ["100042307_0_2000.jpg", "100042307_alt_2000.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_checkered_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Camiseta a cuadros para niño",
      gender: "kid",
    },
    {
      description:
        "Para el futuro viajero espacial con gusto exigente, un mameluco suave de algodón con cierre de broches en la entrepierna. Incluye un etiquetado claro en caso de contacto con una nueva civilización espacial. 100% algodón. Fabricado en Perú",
      images: ["1473809-00-A_1_2000.jpg", "1473809-00-A_alt.jpg"],
      inStock: 16,
      price: 25,
      sizes: ["XS", "S"],
      slug: "made_on_earth_by_humans_onesie",
      type: "shirts",
      tags: ["shirt"],
      title: "Mameluco Made on Earth by Humans",
      gender: "kid",
    },
    {
      description:
        "El mameluco con logo T garabateado para niño está confeccionado con 100% algodón peruano y presenta un logo T de Tesla dibujado para que lo luzca todo pequeño artista.",
      images: ["8529387-00-A_0_2000.jpg", "8529387-00-A_1.jpg"],
      inStock: 0,
      price: 30,
      sizes: ["XS", "S"],
      slug: "scribble_t_logo_onesie",
      type: "shirts",
      tags: ["shirt"],
      title: "Mameluco con logo T garabateado",
      gender: "kid",
    },
    {
      description:
        "Muestra tu compromiso con la energía sostenible con este divertido mameluco para tu pequeño. Nota: no previene las emisiones. 100% algodón. Fabricado en Perú.",
      images: ["1473834-00-A_2_2000.jpg", "1473829-00-A_2_2000.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S"],
      slug: "zero_emissions_(almost)_onesie",
      type: "shirts",
      tags: ["shirt"],
      title: "Mameluco Zero Emissions (Almost)",
      gender: "kid",
    },
    {
      description:
        "Luce tu chaqueta bomber Cyberquad para niño durante tus aventuras en el Cyberquad para niños. La chaqueta bomber presenta una ilustración en estilo graffiti de la silueta y el logotipo de nuestro Cyberquad. Con tres bolsillos con cremallera y el icónico logo T junto con el logotipo de Tesla impresos en las mangas, la chaqueta bomber Cyberquad para niño es perfecta dondequiera que te lleve el camino. Confeccionada con 60% algodón y 40% poliéster.",
      images: ["1742702-00-A_0_2000.jpg", "1742702-00-A_1.jpg"],
      inStock: 10,
      price: 65,
      sizes: ["XS", "S", "M"],
      slug: "kids_cyberquad_bomber_jacket",
      type: "shirts",
      tags: ["shirt"],
      title: "Chaqueta bomber Cyberquad para niño",
      gender: "kid",
    },
    {
      description:
        "Recorre el patio de juegos con estilo con la chaqueta Corp para niños. Modelada a partir de la chaqueta Corp original de Tesla, la chaqueta Corp para niños presenta el mismo estilo sobrio y los mismos materiales de alta calidad, pero en una escala en miniatura.",
      images: ["1506211-00-A_0_2000.jpg", "1506211-00-A_1_2000.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_corp_jacket",
      type: "shirts",
      tags: ["shirt"],
      title: "Chaqueta Corp para niño",
      gender: "kid",
    },
  ],
};
